"""them cot mode cho chat_messages

Revision ID: 65d57f58f042
Revises: d30a18851a31
Create Date: 2026-09-13 05:00:26.437964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d57f58f042'
down_revision: Union[str, Sequence[str], None] = 'd30a18851a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('mode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'mode')
    # ### end Alembic commands ###
